### ISSUE TITLE
Comments in ini files

### ISSUE THREAD

**Issue by lcnittl** [macisamuele/language-formatters-pre-commit-hooks#26] opened 2020-09-12 22:58 UTC
I have realized that `pretty-format-ini` removes comment lines. Is this on purpose?

**Comment by cortinico** [comment] 2020-09-13 09:13
> Is this on purpose?

Nope is not. This is caused by us using `ConfigParser` (https://docs.python.org/2.6/library/configparser.html) that is intentionally skipping comments.

@macisamuele has better context on what we could do to mitigate this.

**Comment by CAM-Gerlach** [comment] 2020-09-28 19:02
Hey, thanks for such a useful set of pre-commit hooks! We're looking to adopt them for the Spyder-IDE organization, starting with our website, themes and documentation. This is a pretty significant issue for us, since it means we can't use this hook on INI files that have comments (many config files), or else they get wiped.

[It appears this can be addressed](https://stackoverflow.com/questions/21476554/update-ini-file-without-removing-comments) by either tricking configparser into thinking that the comments are empty keys without a value, so they pass through without being removed, or by using a different config parser like [ConfigObj](https://github.com/DiffSK/configobj) that preserves them.

While the latter does require another dependency, I would recommend it since the former is a rather crude hack, may not work in edge cases, and it modifies the letter case of the comments unless case normalization is turned off, which means the real keys aren't properly "prettyfied", while the latter has a number of extra features that may end up being useful and is widely used by a number of major projects.

I haven't used it myself (I use TOML and a custom handler for my own config), but I could help implement this if desired, since it should only require changing a few lines in `pretty_format_ini.py`, adding one lightweight dependency in the setup.cfg, plus perhaps modifying a test case to include comments, to verify they are preserved.

Thoughts @cortinico @macisamuele ?

**Comment by macisamuele** [comment] 2020-09-28 19:14
@CAM-Gerlach thanks for your interest and proposal.

I haven't check the proposed lib, but I'm not a fun of "dirty hack" and not really concerned about the additional dependency. 

We always welcome contributions, so feel free to open a PR for it 😅

**Comment by CAM-Gerlach** [comment] 2020-09-28 20:04
Fantastic, thanks @macisamuele ! Now that #37 is merged, I can go ahead with a PR on this once I finish opening issues/PRs to fix a few other issues I ran into, which I'm currently working on testing, confirming and documenting right now.

**Comment by macisamuele** [comment] 2020-09-28 20:38
That's wonderful.
Sorry for the last PRs, they were a bit invasive as a lot changed (style) around :)

**Comment by cortinico** [comment] 2020-09-29 06:25
> I can go ahead with a PR on this

Looking forward to this 🙏 Let us know if you need any support

**Comment by Skylion007** [comment] 2020-10-01 17:11
Please do a new version release ASAP as this is blocking me from using this as a Pre-Commit hook

**Comment by Skylion007** [comment] 2020-11-27 16:08
Any updates on this @CAM-Gerlach ?

**Comment by CAM-Gerlach** [comment] 2020-11-27 18:46
Hey, sorry for the delay; had some major things come up in my personal life and was just getting back to it now. I should be able to work on it in the next few days.

**Closed** 2021-01-05 17:15 UTC
